name: Release Extension

on:
  push:
    tags:
      - 'v*'

# Add permissions section for GitHub releases
permissions:
  contents: write

jobs:
  release:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Setup Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo "DISPLAY=:99.0" >> $GITHUB_ENV
          echo ">>> Started xvfb"

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package Extension
        # Save the packaged file name to a variable
        run: |
          VSIX_FILE=$(vsce package | grep -o '[^/]*\.vsix')
          echo "VSIX_FILE=$VSIX_FILE" >> $GITHUB_ENV
          echo "Packaged extension as $VSIX_FILE"

      - name: Publish to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.VSIX_FILE }}
          generate_release_notes: true 